let products = [
  // Kurti & Dress (15)
  {id:1,name:"Floral Kurti",category:"Kurti & Dress",gender:"Female",price:1200,img:"https://i.imgur.com/1.jpg",offer:"20% OFF",rating:4.5},
  {id:2,name:"Silk Saree",category:"Kurti & Dress",gender:"Female",price:2500,img:"https://i.imgur.com/2.jpg",offer:"15% OFF",rating:4.8},
  {id:3,name:"Anarkali Dress",category:"Kurti & Dress",gender:"Female",price:1800,img:"https://i.imgur.com/3.jpg",offer:"10% OFF",rating:4.2},
  {id:4,name:"Cotton Kurti",category:"Kurti & Dress",gender:"Female",price:1000,img:"https://i.imgur.com/4.jpg",offer:"25% OFF",rating:4.1},
  {id:5,name:"Party Gown",category:"Kurti & Dress",gender:"Female",price:2200,img:"https://i.imgur.com/5.jpg",offer:"20% OFF",rating:4.6},
  {id:6,name:"Straight Kurti",category:"Kurti & Dress",gender:"Female",price:1100,img:"https://i.imgur.com/6.jpg",offer:"15% OFF",rating:4.3},
  {id:7,name:"Designer Saree",category:"Kurti & Dress",gender:"Female",price:3000,img:"https://i.imgur.com/7.jpg",offer:"10% OFF",rating:4.7},
  {id:8,name:"Maxi Dress",category:"Kurti & Dress",gender:"Female",price:2000,img:"https://i.imgur.com/8.jpg",offer:"20% OFF",rating:4.2},
  {id:9,name:"Ethnic Kurti",category:"Kurti & Dress",gender:"Female",price:1300,img:"https://i.imgur.com/9.jpg",offer:"15% OFF",rating:4.4},
  {id:10,name:"Long Dress",category:"Kurti & Dress",gender:"Female",price:1700,img:"https://i.imgur.com/10.jpg",offer:"10% OFF",rating:4.1},
  {id:11,name:"Printed Saree",category:"Kurti & Dress",gender:"Female",price:2600,img:"https://i.imgur.com/11.jpg",offer:"15% OFF",rating:4.5},
  {id:12,name:"Palazzo Kurti",category:"Kurti & Dress",gender:"Female",price:1400,img:"https://i.imgur.com/12.jpg",offer:"20% OFF",rating:4.2},
  {id:13,name:"Layered Dress",category:"Kurti & Dress",gender:"Female",price:2300,img:"https://i.imgur.com/13.jpg",offer:"10% OFF",rating:4.6},
  {id:14,name:"Chiffon Kurti",category:"Kurti & Dress",gender:"Female",price:1500,img:"https://i.imgur.com/14.jpg",offer:"15% OFF",rating:4.3},
  {id:15,name:"Gota Work Saree",category:"Kurti & Dress",gender:"Female",price:2800,img:"https://i.imgur.com/15.jpg",offer:"20% OFF",rating:4.7},

  // Kids & Toys (10)
  {id:16,name:"Toy Car",category:"Kids & Toys",gender:"Kids",price:500,img:"https://i.imgur.com/16.jpg",offer:"10% OFF",rating:4.0},
  {id:17,name:"Doll Set",category:"Kids & Toys",gender:"Kids",price:800,img:"https://i.imgur.com/17.jpg",offer:"15% OFF",rating:4.5},
  {id:18,name:"Puzzle Game",category:"Kids & Toys",gender:"Kids",price:300,img:"https://i.imgur.com/18.jpg",offer:"20% OFF",rating:4.2},
  {id:19,name:"Building Blocks",category:"Kids & Toys",gender:"Kids",price:700,img:"https://i.imgur.com/19.jpg",offer:"10% OFF",rating:4.3},
  {id:20,name:"Board Game",category:"Kids & Toys",gender:"Kids",price:600,img:"https://i.imgur.com/20.jpg",offer:"15% OFF",rating:4.1},
  {id:21,name:"Action Figure",category:"Kids & Toys",gender:"Kids",price:400,img:"https://i.imgur.com/21.jpg",offer:"20% OFF",rating:4.4},
  {id:22,name:"Stuffed Toy",category:"Kids & Toys",gender:"Kids",price:450,img:"https://i.imgur.com/22.jpg",offer:"10% OFF",rating:4.2},
  {id:23,name:"Water Gun",category:"Kids & Toys",gender:"Kids",price:350,img:"https://i.imgur.com/23.jpg",offer:"15% OFF",rating:4.0},
  {id:24,name:"Crayons Set",category:"Kids & Toys",gender:"Kids",price:200,img:"https://i.imgur.com/24.jpg",offer:"20% OFF",rating:4.3},
  {id:25,name:"Mini Guitar",category:"Kids & Toys",gender:"Kids",price:900,img:"https://i.imgur.com/25.jpg",offer:"10% OFF",rating:4.5},

  // Westernwear (10)
  {id:26,name:"Denim Jacket",category:"Westernwear",gender:"Female",price:2000,img:"https://i.imgur.com/26.jpg",offer:"15% OFF",rating:4.4},
  {id:27,name:"T-Shirt",category:"Westernwear",gender:"Male",price:800,img:"https://i.imgur.com/27.jpg",offer:"10% OFF",rating:4.2},
  {id:28,name:"Jeans",category:"Westernwear",gender:"Male",price:1200,img:"https://i.imgur.com/28.jpg",offer:"20% OFF",rating:4.3},
  {id:29,name:"Skater Dress",category:"Westernwear",gender:"Female",price:1500,img:"https://i.imgur.com/29.jpg",offer:"15% OFF",rating:4.5},
  {id:30,name:"Hoodie",category:"Westernwear",gender:"Female",price:1800,img:"https://i.imgur.com/30.jpg",offer:"10% OFF",rating:4.1},
  {id:31,name:"Shirt",category:"Westernwear",gender:"Male",price:1000,img:"https://i.imgur.com/31.jpg",offer:"20% OFF",rating:4.2},
  {id:32,name:"Shorts",category:"Westernwear",gender:"Male",price:700,img:"https://i.imgur.com/32.jpg",offer:"15% OFF",rating:4.0},
  {id:33,name:"Blouse",category:"Westernwear",gender:"Female",price:1200,img:"https://i.imgur.com/33.jpg",offer:"10% OFF",rating:4.4},
  {id:34,name:"Sweater",category:"Westernwear",gender:"Female",price:1600,img:"https://i.imgur.com/34.jpg",offer:"15% OFF",rating:4.3},
  {id:35,name:"Cap",category:"Westernwear",gender:"Male",price:500,img:"https://i.imgur.com/35.jpg",offer:"20% OFF",rating:4.1},

  // Home (10)
  {id:36,name:"Cushion Cover",category:"Home",gender:"Unisex",price:400,img:"https://i.imgur.com/36.jpg",offer:"10% OFF",rating:4.2},
  {id:37,name:"Wall Clock",category:"Home",gender:"Unisex",price:600,img:"https://i.imgur.com/37.jpg",offer:"15% OFF",rating:4.3},
  {id:38,name:"Table Lamp",category:"Home",gender:"Unisex",price:1200,img:"https://i.imgur.com/38.jpg",offer:"20% OFF",rating:4.5},
  {id:39,name:"Curtains",category:"Home",gender:"Unisex",price:1500,img:"https://i.imgur.com/39.jpg",offer:"10% OFF",rating:4.1},
  {id:40,name:"Rug",category:"Home",gender:"Unisex",price:2000,img:"https://i.imgur.com/40.jpg",offer:"15% OFF",rating:4.4},
  {id:41,name:"Vase",category:"Home",gender:"Unisex",price:700,img:"https://i.imgur.com/41.jpg",offer:"20% OFF",rating:4.2},
  {id:42,name:"Photo Frame",category:"Home",gender:"Unisex",price:300,img:"https://i.imgur.com/42.jpg",offer:"10% OFF",rating:4.3},
  {id:43,name:"Kitchen Set",category:"Home",gender:"Unisex",price:2500,img:"https://i.imgur
